
server:
  port: 6001

spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fenglixiong123/microservicecloud-config.git
          basedir: D:\workcode\myreposity #本地存储路径
          search-paths: /user-app/,/dept-app/     #远程相对路径



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true



info:
  app.name: ${spring.application.name}
  company.name: www.fenglixiong.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}