server:
  port: 9001

spring:
  application:
    name: microservice-provider-user
#  boot:
#    admin:
#      client:
#        url: http://localhost:9999                  #admin server注册地址

eureka:                                               # 客户端注册进入eureka服务列表内
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}  #别名处理，显示在页面status
    prefer-ip-address: true                                 #鼠标放在微服务名字上面显示IP地址

#用于显示info信息
info:
  app.name: ${spring.application.name}
  company.name: www.fenglixiong.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}