server:
  port: 80

spring:
  application:
    name: consumer-dept-ribbon

eureka:                                               # 客户端注册进入eureka服务列表内
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}  #别名处理，显示在页面status
    prefer-ip-address: true


