server:
  port: 9999

spring:
  application:
    name: microservice-boot-admin

eureka:                                               # 客户端注册进入eureka服务列表内
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}  #别名处理，显示在页面status
    prefer-ip-address: true


#用于显示info信息
info:
  app.name: ${spring.application.name}
  company.name: www.fenglixiong.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}