server:
  port: 8001

#整合Mybatis
mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis 配置文件所在路径
  type-aliases-package: com.flx.springboot.entity     #所有entity别名所在的包
  mapper-locations:                                   #mapper配置文件
    - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservice-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01        #数据库驱动名称
    username: root
    password: welcome
    dbcp2:
      min-idle: 5                                     #最小连接数
      initial-size: 5                                 #初始化连接数
      max-total: 5                                    #最大连接数
      max-wait-millis: 200                            #最大超时时间


eureka:                                               # 客户端注册进入eureka服务列表内
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}  #别名处理，显示在页面status
    prefer-ip-address: true                                 #鼠标放在微服务名字上面显示IP地址

#用于显示info信息
info:
  app.name: ${spring.application.name}
  company.name: www.fenglixiong.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}


