server:
  port: 80

spring:
  application:
    name: consumer-dept-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

#开启hystrix服务
feign:
  hystrix:
    enabled: true

#用于显示info信息
info:
  app.name: ${spring.application.name}
  company.name: www.fenglixiong.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}